language: elixir
elixir:
  - 1.7.4
  - 1.8.2
  - 1.9.4

cache:
  directories:
    - _build
    - deps

notifications:
  email: true

otp_release:
  - 20.0

script:
  - "mix do deps.get, compile"
  - MIX_ENV=test mix coveralls.travis
